name: Update Data
on:
  workflow_dispatch: ~
  schedule:
    - cron: "*/10 * * * *"
concurrency: one-at-a-time
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-python@v3
        with:
          python-version: ">=3.10"
      - run: pip install poetry && poetry install
      - run: poetry run python update.py push
